# Artificial Neural Network (ANN)
## Tensorflow Documentation for Keras
### Link : https://www.tensorflow.org/guide/keras/sequential_model

### Librerias

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

## Modelo Sequential
### Modelo Sequential estatico.

In [2]:
model = keras.Sequential(
    [
        layers.Dense(units = 2, activation = 'relu', name = 'HiddenLayer1'),
        layers.Dense(units = 3, activation = 'relu', name = 'HiddenLayer2'),
        layers.Dense(units = 4, name = 'HiddenLayer3')
    ]
)

In [3]:
print(len(model.layers))

3


### Modelo Sequential Dinamico

In [4]:
model = keras.Sequential()
model.add(layers.Dense(units = 2, activation = 'relu', name = 'HiddenLayer1'))
model.add(layers.Dense(units = 3, activation = 'relu', name = 'HiddenLayer2'))
model.add(layers.Dense(units = 4))

In [5]:
print(len(model.layers))

3


### Eliminar una capa del modelo

In [6]:
print(len(model.layers))
print(model.layers)

# Metodo pop() para eliminar una capa del modelo (borra la ultima capa).
model.pop()
print(len(model.layers))
print(model.layers)

3
[<keras.layers.core.dense.Dense object at 0x7f7c337fcb90>, <keras.layers.core.dense.Dense object at 0x7f7c337fc9d0>, <keras.layers.core.dense.Dense object at 0x7f7c20021850>]
2
[<keras.layers.core.dense.Dense object at 0x7f7c337fcb90>, <keras.layers.core.dense.Dense object at 0x7f7c337fc9d0>]


## Espeificando pesos
### Especificar los pesos de una capa

In [7]:
layer = layers.Dense(units = 3)
print(layer.weights)
# Lo pesos de la capa no fueron especificados en la construccion de la capa,
# por loq ue la capa no tiene pesos inicialzados.

[]


In [8]:
# Array Bi_Dimensional de 1 fila con 4 columnas rellena con valores de 1.
x = tf.ones((1, 4))
print("x :" + str(x))

y = layer(x)

print("Weights : " + str(layer.weights))

x :tf.Tensor([[1. 1. 1. 1.]], shape=(1, 4), dtype=float32)
Weights : [<tf.Variable 'dense_1/kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.11953533,  0.48468912, -0.08332574],
       [-0.46367908, -0.70256   ,  0.48894942],
       [ 0.7501943 , -0.8966882 , -0.33947718],
       [ 0.4939195 ,  0.2528677 ,  0.14792466]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]


### Especificar los pesos de un Incremental Sequential model

Alternativa 1

In [9]:
# Modelo incremental
model = keras.Sequential()
# Definir que los Input Features del modelo seran de 4 filas con 1 columna.
model.add(keras.Input(shape = (4, )))
model.add(layers.Dense(units = 2, activation = 'relu'))

print(model.weights)

[<tf.Variable 'dense_2/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[-0.24231577,  0.57282305],
       [-0.3334012 ,  0.33863878],
       [ 0.43488216, -0.4714365 ],
       [-0.6702287 , -0.14267993]], dtype=float32)>, <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]


In [10]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


Alternativa 2

In [11]:
model = keras.Sequential()
model.add(layers.Dense(units = 2, activation = 'relu', input_shape = (4, )))
model.add(layers.Dense(units = 3, activation = 'relu'))
model.add(layers.Dense(units = 4))

print(model.weights)

[<tf.Variable 'dense_3/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.14110398,  0.5272341 ],
       [-0.816895  ,  0.12437654],
       [ 0.35521817, -0.9553673 ],
       [-0.51500916, -0.0595305 ]], dtype=float32)>, <tf.Variable 'dense_3/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>, <tf.Variable 'dense_4/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.6255364 ,  0.36221683,  0.02241898],
       [-0.4233231 , -0.5707519 ,  0.83297765]], dtype=float32)>, <tf.Variable 'dense_4/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_5/kernel:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.49736732, -0.5448286 , -0.5508621 ,  0.30417812],
       [ 0.8691435 , -0.1361751 , -0.3543824 , -0.6888693 ],
       [-0.87149006,  0.46367383, -0.13790959,  0.34496987]],
      dtype=float32)>, <tf.Variable 'dense_5/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


In [12]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 2)                 10        
                                                                 
 dense_4 (Dense)             (None, 3)                 9         
                                                                 
 dense_5 (Dense)             (None, 4)                 16        
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


### Especificar los pesos de un Estatic Sequential Model
Los pesos se crean automaticamente cuando el modelo comienza a recibir los Input Features

In [13]:
# Modelo Estatico
model = keras.Sequential(
    [
        layers.Dense(units = 2, activation = 'relu'),
        layers.Dense(units = 3, activation = 'relu'),
        layers.Dense(units = 4),
    ]
)

x = tf.ones((1, 4))
y = model(x)

print(model.weights)

[<tf.Variable 'dense_6/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.06413388, -0.6293013 ],
       [ 0.00500798,  0.35406923],
       [ 0.5427861 , -0.97585225],
       [ 0.4088719 , -0.3950944 ]], dtype=float32)>, <tf.Variable 'dense_6/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>, <tf.Variable 'dense_7/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.4750421 , -0.68229556, -0.8413548 ],
       [-0.33997685, -0.87198454,  0.26879084]], dtype=float32)>, <tf.Variable 'dense_7/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_8/kernel:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.21810186,  0.10764718,  0.61716115, -0.55959713],
       [ 0.7821003 , -0.7365418 ,  0.91537833,  0.54827225],
       [ 0.6147764 , -0.557605  ,  0.806219  , -0.5094242 ]],
      dtype=float32)>, <tf.Variable 'dense_8/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


In [14]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (1, 2)                    10        
                                                                 
 dense_7 (Dense)             (1, 3)                    9         
                                                                 
 dense_8 (Dense)             (1, 4)                    16        
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Transferir aprendizaje con un modelo Sequential
### El aprendizaje por transferencia consiste en congelar las capas inferiores en un modelo y solo entrenar las capas superiores.

Congelar todas las capas excepto la ultima

In [15]:
model = keras.Sequential(
    [
        keras.Input(shape = (784, )),
        layers.Dense(units = 32, activation = 'relu'),
        layers.Dense(units = 32, activation = 'relu'),
        layers.Dense(units = 32, activation = 'relu'),
        layers.Dense(units = 10),
    ]
)

# model.load_weights(1)
print(model.weights)

[<tf.Variable 'dense_9/kernel:0' shape=(784, 32) dtype=float32, numpy=
array([[-0.08300833,  0.08090162, -0.03481584, ...,  0.02569134,
         0.06759246, -0.0391703 ],
       [ 0.07669403, -0.0271625 , -0.05536924, ...,  0.07847706,
         0.0784407 ,  0.08445214],
       [ 0.07793022, -0.06658705, -0.01538555, ...,  0.04780949,
         0.00553027, -0.0001839 ],
       ...,
       [ 0.02281398, -0.01974178, -0.06081155, ..., -0.03739359,
        -0.06337628,  0.05684022],
       [-0.01640097, -0.03582237, -0.02063274, ..., -0.00838289,
         0.03778947, -0.01592963],
       [ 0.06552406,  0.07181177,  0.02735797, ...,  0.08229334,
        -0.05981275, -0.06457711]], dtype=float32)>, <tf.Variable 'dense_9/bias:0' shape=(32,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, <tf.Variable 'dense_10/kernel:0' shape=(32, 32) dtype=float32, numpy=

In [16]:
# Congelar todas las capas escepto la ultima
for layer in model.layers[:-1]:
  layer.trainable = False

print(model.layers)

[<keras.layers.core.dense.Dense object at 0x7f7bb6753c50>, <keras.layers.core.dense.Dense object at 0x7f7bb6755050>, <keras.layers.core.dense.Dense object at 0x7f7bb6755350>, <keras.layers.core.dense.Dense object at 0x7f7bb6755710>]


## Apilar capas al modelo despues de creado
### Incremental Sequential Model

In [22]:
model = keras.Sequential()
model.add(keras.Input(128, ))
model.add(layers.Dense(units = 64, activation = 'relu'))
model.add(layers.Dense(units = 32, activation = 'relu'))

In [23]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 64)                8256      
                                                                 
 dense_18 (Dense)            (None, 32)                2080      
                                                                 
Total params: 10,336
Trainable params: 10,336
Non-trainable params: 0
_________________________________________________________________


In [24]:
# Aplilar nueva capas al modelo exixtente
model.add(layers.Dense(units = 16, activation = 'relu'))
model.add(layers.Dense(units = 8, activation = 'relu'))

In [25]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 64)                8256      
                                                                 
 dense_18 (Dense)            (None, 32)                2080      
                                                                 
 dense_19 (Dense)            (None, 16)                528       
                                                                 
 dense_20 (Dense)            (None, 8)                 136       
                                                                 
Total params: 11,000
Trainable params: 11,000
Non-trainable params: 0
_________________________________________________________________


In [26]:
# Output Layer
model.add(layers.Dense(units = 1, activation = 'sigmoid'))
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 64)                8256      
                                                                 
 dense_18 (Dense)            (None, 32)                2080      
                                                                 
 dense_19 (Dense)            (None, 16)                528       
                                                                 
 dense_20 (Dense)            (None, 8)                 136       
                                                                 
 dense_21 (Dense)            (None, 1)                 9         
                                                                 
Total params: 11,009
Trainable params: 11,009
Non-trainable params: 0
_________________________________________________________________


## Estraccion de caracteristicas de las capas del model
### Las caracteristicas 'Inputs' y 'Outputs' de cada una de las capas del modelo

In [38]:
"""
model = keras.Sequential()
model.add(keras.Input(shape = (128, )))
model.add(layers.Dense(units = 32, activation = 'relu'))
model.add(layers.Dense(units = 16, activation = 'relu'))
model.add(layers.Dense(units = 1))
"""

# Modelo Estatico
model = keras.Sequential(
    [
        keras.Input(shape = (128, )),
        layers.Dense(units = 32, activation = 'relu'),
        layers.Dense(units = 16, activation = 'relu'),
        layers.Dense(units = 1),
    ]
)

features_extractor = keras.Model(
    inputs = model.inputs,
    outputs = [layer.output for layer in model.layers],
)

x = tf.ones((128,))
# NO SE POR QUE NO FUNCION.
# En modelos Convolucionales si funciona, ver el archivo uno de CNN
features = features_extractor(x)

print(features)

ValueError: ignored