# Convolution Neural Network (CNN)
## Tensorflow Documentation for Keras
### Link : https://www.tensorflow.org/guide/keras/sequential_model

### Librerias

In [19]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

## Apilar capas al modelo despues de creado
### Convolutional Model

In [20]:
model = keras.Sequential()
model.add(keras.Input(shape = (250, 250, 3))) # 250x250 RGB images.
# filters : numero de filtros de salida en la convolucion de cada imagen.
# kernel_size : altura y ancho de la ventana de convolucion.
# strides : zancada --> la matriz de convolucion dentro de la imagen se corre 
# 2 pixeles en cada convolucion.
model.add(layers.Conv2D(filters = 32, kernel_size = 5, strides = 2, activation = 'relu'))
model.add(layers.Conv2D(32, 3, activation = 'relu'))
model.add(layers.MaxPool2D(3))

In [21]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_25 (Conv2D)          (None, 123, 123, 32)      2432      
                                                                 
 conv2d_26 (Conv2D)          (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 40, 40, 32)       0         
 2D)                                                             
                                                                 
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.add(layers.Conv2D(32, 3, activation = 'relu'))
model.add(layers.Conv2D(32, 3, activation = 'relu'))
model.add(layers.MaxPool2D(3))
model.add(layers.Conv2D(32, 3, activation = 'relu'))
model.add(layers.Conv2D(32, 3, activation = 'relu'))
model.add(layers.MaxPool2D(2))

In [23]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_25 (Conv2D)          (None, 123, 123, 32)      2432      
                                                                 
 conv2d_26 (Conv2D)          (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 40, 40, 32)       0         
 2D)                                                             
                                                                 
 conv2d_27 (Conv2D)          (None, 38, 38, 32)        9248      
                                                                 
 conv2d_28 (Conv2D)          (None, 36, 36, 32)        9248      
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 12, 12, 32)       0         
 2D)                                                  

## Estraccion de caracteristicas de las capas del model
### Las caracteristicas 'Inputs' y 'Outputs' de cada una de las capas del modelo

In [24]:
model = keras.Sequential(
    [
        keras.Input(shape = (250, 250, 3)),
        layers.Conv2D(filters = 32, kernel_size = 5, strides = 2, activation = 'relu'),
        layers.Conv2D(32, 3, activation = 'relu'),
        layers.Conv2D(32, 3, activation = 'relu'),
    ]
)

feature_extractor = keras.Model(
    
    inputs = model.inputs,
    outputs = [layer.output for layer in model.layers],
)

x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
print(features)

[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
array([[[[0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         [0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         [0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         [0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         [0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ]],

        [[0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         [0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         [0.        , 0.        , 0.        , ..., 0.20594102,
          0.        , 0.5362094 ],
         ...,
         [0.        , 0.    

### Las caracteristicas 'Inputs' y 'Outputs' de una sola capa del modelo

In [25]:
model = keras.Sequential(
    [
        keras.Input(shape = (250, 250, 3)),
        layers.Conv2D(32, 5, strides = 2, activation = 'relu', name = 'Hidden1'),
        layers.Conv2D(32, 3, activation = 'relu', name = 'Hidden2'),
        layers.Conv2D(32, 3, activation = 'relu', name = 'Hidden3'),
    ]
)

feature_extractor = keras.Model(
    
    inputs = model.inputs,
    outputs = model.get_layer(name = 'Hidden2').output,
)

x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)

print(features)

tf.Tensor(
[[[[0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   ...
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]]

  [[0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   ...
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]
   [0.         0.         0.         ... 0.1680421  0.06766389
    0.        ]]

  [[0.         0.      