# Tensores y operaciones con tensores

## Tensores

El **tensor** es el elemento fundamental de Tensorflow. En términos prácticos, un tensor es similar a una _ndarray_ de NumPy, es decir, un array multidimensional. La diferencia principal es que los tensores admiten una gama más amplia de valores, por ejemplo, un único escalar (un valor simple como el número 15)

In [1]:
# Importamos tensorflow
import tensorflow as tf

tf.__version__

'2.8.2'

Podemos comenzar definiendo un tensor con Tensorflow mediante el método _tf.constant()_

In [3]:
# El tensor representa una matriz
tf.constant([[1., 2., 3.], [4., 5., 6.]])
# shape: 2 filas y 3 columnas

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
# El tensor representa un escalar
tf.constant(15)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

Al igual que un _ndarray_ de NumPy, un tensor tiene una forma (_shape_) y un tipo (_dtype_)

In [5]:
t = tf.constant([[1., 2.],[3., 4.]])
t.shape

TensorShape([2, 2])

In [6]:
t.dtype

tf.float32

## Acceso a los elementos de un Tensor

La manera de indexar los valores de un tensor es igual a la que se utiliza para indexar los elementos de un _ndarray_ de NumPy

In [7]:
# Definicion de un tensor que representa una matriz
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [10]:
# Acceso a la segunda fila del tensor
t[1,:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

In [12]:
# Acceso a la tercera columna del tensor
t[:, 2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 6.], dtype=float32)>

## Operaciones con Tensores

Uno de los aspectos más relevantes de los tensores es que podemos realizar todo tipo de operaciones con ellos.

In [13]:
# Definicion de un tensor que representa una matriz
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [15]:
# Suma de un tensor y un escalar
print(t)
print(t + 10)
# El numero Escalar se suma a cada uno de los valores del tensor

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)


In [17]:
# Suma de dos tensores
print(t + t)
# Cada numero del tensor es sumado a su corresponsal, igual como se hace al sumar matrices.

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


In [18]:
# Cuadrado de un tensor
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

Tensorflow nos proporciona una amplia gama de funciones matemáticas que podemos utilizar para operar con tensores:
* tf.exp()
* tf.sqrt()
* tf.transpose()
* ...

## Tensores y conversión de tipos

Una de las cosas relevantes que se debe tener en cuenta cuando se utiliza Tensorflow, es que no realiza conversión de tipos al realizar una operacion. Esto quiere decir que si no se utilizan valores del mismo tipo en la operacion, se producira una excepcion.

In [23]:
# Creacion de dos Tensores de tipos diferentes
t1 = tf.constant(1.0)
t2 = tf.constant(2)
# Tensorflow no permite sumar Tensores de tipo diferente, Numpy tampoco.

In [24]:
print("Tipo t1:", t1.dtype)
print("Tipo t2:", t2.dtype)

Tipo t1: <dtype: 'float32'>
Tipo t2: <dtype: 'int32'>


In [25]:
try:
    t3 = t1 + t2
except Exception as e:
    print("Exception:", e)

Exception: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]


In [22]:
try:
    tf.constant([1, 2, 3]) + tf.constant([1.0, 2.0, 3.0])
except Exception as e:
    print("Exception:", e)

Exception: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]


## Tensores variables

Hasta ahora, la estructuras de Tensorflow que hemos utilizado para almacenar valores son inmutables, esto quiere decir que no podemos realizar modificaciones una vez se han creado.

In [26]:
# motodo 'constant()' crea un Tensor inmutable, como una tuplan.
t = tf.constant([1.0, 2.0, 3.0])
t[0] = 4.0

TypeError: ignored

Si necesitamos crear una estructura que pueda modificarse despues de haber sido creada, entonces tenemos que utilizar _tf.Variable_

In [27]:
# el metodo 'Variable()' si permite crear un Tensor modificable.
t = tf.Variable([1.0, 2.0, 3.0])
print("Tensor original:", t.value())

t[0].assign(2.0)
print("Tensor modificado:", t.value()) 

Tensor original: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Tensor modificado: tf.Tensor([2. 2. 3.], shape=(3,), dtype=float32)


Tensorflow soporta otros tipos de estructuras de datos como las cadenas de texto

In [28]:
tf.constant(b"hola mundo")

<tf.Tensor: shape=(), dtype=string, numpy=b'hola mundo'>

In [29]:
tf.constant("españa")

<tf.Tensor: shape=(), dtype=string, numpy=b'espa\xc3\xb1a'>

In [31]:
t2 = tf.constant(["hola", "mundo", "españa"]) # array unidimensional

In [33]:
t2.shape

TensorShape([3])

In [40]:
t2[1]

<tf.Tensor: shape=(), dtype=string, numpy=b'mundo'>

In [42]:
t3 = tf.constant([["Super", "Ku"],["Ideal", "Dummy"]])

In [43]:
t3[:, 1]

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Ku', b'Dummy'], dtype=object)>