# ANN : Aritficial Neural Network
# RNA : Red Neuronal Artificial
### Construccion de una ANN para un DataSet de datos bancario de clientes.
### Buscamos la probabilidad de que un cliente abandone el banco usando un modelo de Clasificacion.

# Acceso a mi data set en One Drive

In [72]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [73]:
ls

drive/  sample_data/


In [74]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

## Instalar librerias
Librerias para construir el ambiente de trabajo.

In [75]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [76]:
# !git clone https://github.com/Theano/Theano.git
# !pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

In [77]:
!pip install --upgrade --no-deps Theano

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [78]:
!pip install keras
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Artificial Neural Network Build
Instalar librerias

In [79]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar DataSet

In [80]:
dataset = pd.read_csv('/content/drive/MyDrive/AI Courses Udemy/Deep/Course 2/ANN/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [81]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [82]:
# Eliminar columnas de strings (0,2,3) del narray.
# X = np.delete(X, (0,2,3), axis=1) 
# Convertir las columnas a tipo 'float'
# X = X.astype(float)
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [83]:
y[0]

1

# Pre procesado de datos
### Codificar datos Categoricos

In [84]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [85]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers = [
        ('Churn_Modelling',
         OneHotEncoder(sparse=False, categories = 'auto'), [1])
    ], remainder = 'passthrough'                
)
X = transformer.fit_transform(X)
X = X[:, 1:]

In [86]:
X[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [87]:
""" ## Versiones superiores a python 3.7
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
     
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   
    remainder='passthrough'                        
)
X = np.array(ct.fit_transform(X), dtype=np.float)
"""

" ## Versiones superiores a python 3.7\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\n     \nct = ColumnTransformer(\n    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   \n    remainder='passthrough'                        \n)\nX = np.array(ct.fit_transform(X), dtype=np.float)\n"

In [88]:
!python --version

Python 3.7.14


# Dividir el DataSet en conjunto de Training y Testing

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [90]:
X_train[0]

array([0.0, 1.0, 667, 0, 34, 5, 0.0, 2, 1, 0, 163830.64], dtype=object)

In [91]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [92]:
X_train[0]

array([-0.5698444 ,  1.74309049,  0.16958176, -1.09168714, -0.46460796,
        0.00666099, -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,
        1.10643166])

In [93]:
X_test[0]

array([ 1.75486502, -0.57369368, -0.55204276, -1.09168714, -0.36890377,
        1.04473698,  0.8793029 , -0.92159124,  0.64259497,  0.9687384 ,
        1.61085707])

# Construir la ANN
## Importar Keras y librerias adicionales

In [94]:
import keras 
from keras.models import Sequential
from keras.layers import Dense

## Inicializar la ANN
### El modelo va a Clasificar.

In [95]:
classifier = Sequential()

## Añadir capa de entrada, capas ocultas y capa de salida

In [96]:
# Para conocer la cantidad de 'Input Features' hago lo siguiente
len(X_train[0])

11

In [97]:
# Dense : define la sinapsis (cantidad de 'Input Features' que recibira la 'Hidden Layer'), y define la 'Hidden Layer' y sus 'Output Features'.
# Units : por recomendacion del profesor se escojen la cantidad de neuronas que corresponden a la media de 'Input Features'.
# Input_Dim : definimos la cantidad de 'Input Features' que recibira la 'Hidden Layer'.
# Kernel:Inicializer : definimos los valores de inicializacion de los parametros de la ANN.
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# 'Hidden Layer' 2
# 'Input_Dim' no es necesario especificarla (no especificar la cantidad de 'Input Features')
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# 'Output Layer'
# Modelo de Clasificacion (dos clases de salida).
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

## Compilar la ANN

In [98]:
# optimizar : Optimization Function como Stochastic Greadient Descent.
# loss : Error/Costo Function.
# metrics : metrica de para ir visualizando el rendimiento del entrenamiento del modelo.
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training del modelo de ANN

In [99]:
# batch_size : contenedor/porcion de datos del conjunto de datos de entrenamiento de 32 datos.
# --> ingesta de paquetes de 32 datos a la ANN para que se entrene.
# epochs : numero de ingesta completa del conjunto de datos de entrenamiento a la ANN.
classifier.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4350 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4284 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4247 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4220 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4196 - accuracy: 0.7983
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4183 - accuracy: 0.8210
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4170 - accuracy: 0.8223
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4160 - accuracy: 0.8230
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4150 - accura

## Prediccion y evaluacion de la ANN

In [103]:
y_pred = classifier.predict(X_test)

In [112]:
# Trnasformar los datos de prediccion a booleanos.
# --> los verdaderos son clientes que se van del banco.
# --> los falsos son clientes que se quedan en el banco.
print(y_pred)
print(y_pred > 0.5)

[[0.21984062]
 [0.39718676]
 [0.16821782]
 ...
 [0.16284627]
 [0.17654873]
 [0.14155263]]
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [114]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

ValueError: ignored

## Probar la ANN con un dato nuevo

###Utiliza nuestro modelo de RNA para predecir si el cliente con la siguiente información abandonará el banco:

*   Geografia: Francia (dos columnas)
*   Puntaje de crédito: 600
*   Género masculino
*   Edad: 40 años de edad
*   Tenencia: 3 años.
*   Saldo: $ 60000

*   Número de productos: 2
*   ¿Este cliente tiene una tarjeta de crédito? Sí
*   ¿Es este cliente un miembro activo? Sí
*   Salario estimado: $ 50000

In [108]:
dataset.iloc[0, 3:13].values

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [109]:
X[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [110]:
# En el DataSet son 3 paises, por lo cual son dos columnas para especificar a cual corresponde (Variable Dummy)
# Escalar los datos de la nueva prediccion con : sc_X.transform()
# new_prediction = classifier.predict(sc_X.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = classifier.predict(sc_X.transform(np.array([[0,0,600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
print(new_prediction)
print(new_prediction > 0.5)

[[0.09016236]]
[[False]]


In [111]:
print((cm[0][0]+cm[1][1])/cm.sum())

0.86
