# ANN : Aritficial Neural Network
# RNA : Red Neuronal Artificial
### Construccion de una ANN para un DataSet de datos bancario de clientes.
### Buscamos la probabilidad de que un cliente abandone el banco usando un modelo de Clasificacion.

# Acceso a mi data set en One Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!ls

drive  sample_data


In [3]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

## Instalar librerias
Librerias para construir el ambiente de trabajo.

In [4]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=e0ff66620f3d496981d417ee68b55c1ba17e8598b7cc997390cc0c91368f857a
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [5]:
# !git clone https://github.com/Theano/Theano.git
# !pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

In [6]:
!pip install --upgrade --no-deps Theano

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.8 MB 24.7 MB/s 
  Created wheel for Theano: filename=Theano-1.0.5-py3-none-any.whl size=2668111 sha256=b16b5b27823dff44e3d5a24d97042ce3ebdc77eeaa97331e468677a2ba723238
  Stored in directory: /root/.cache/pip/wheels/26/68/6f/745330367ce7822fe0cd863712858151f5723a0a5e322cc144
Successfully built Theano


In [7]:
!pip install keras
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Artificial Neural Network Build
Instalar librerias

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar DataSet

In [9]:
dataset = pd.read_csv('/content/drive/MyDrive/AI Courses Udemy/Deep/Course 2/ANN/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [10]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [11]:
# Eliminar columnas de strings (0,2,3) del narray.
# X = np.delete(X, (0,2,3), axis=1) 
# Convertir las columnas a tipo 'float'
# X = X.astype(float)
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [12]:
y[0]

1

# Pre procesado de datos
### Codificar datos Categoricos

In [13]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers = [
        ('Churn_Modelling',
         OneHotEncoder(sparse=False, categories = 'auto'), [1])
    ], remainder = 'passthrough'                
)
X = transformer.fit_transform(X)
X = X[:, 1:]

In [15]:
X[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [16]:
""" ## Versiones superiores a python 3.7
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
     
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   
    remainder='passthrough'                        
)
X = np.array(ct.fit_transform(X), dtype=np.float)
"""

" ## Versiones superiores a python 3.7\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\n     \nct = ColumnTransformer(\n    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   \n    remainder='passthrough'                        \n)\nX = np.array(ct.fit_transform(X), dtype=np.float)\n"

In [17]:
!python --version

Python 3.7.14


# Dividir el DataSet en conjunto de Training y Testing

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [19]:
X_train[0]

array([0.0, 1.0, 667, 0, 34, 5, 0.0, 2, 1, 0, 163830.64], dtype=object)

In [20]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [21]:
X_train[0]

array([-0.5698444 ,  1.74309049,  0.16958176, -1.09168714, -0.46460796,
        0.00666099, -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,
        1.10643166])

In [22]:
X_test[0]

array([ 1.75486502, -0.57369368, -0.55204276, -1.09168714, -0.36890377,
        1.04473698,  0.8793029 , -0.92159124,  0.64259497,  0.9687384 ,
        1.61085707])

# Construir la ANN
## Importar Keras y librerias adicionales

In [23]:
import keras 
from keras.models import Sequential
from keras.layers import Dense

## Inicializar la ANN
### El modelo va a Clasificar.

In [24]:
classifier = Sequential()

## Añadir capa de entrada, capas ocultas y capa de salida

In [25]:
# Para conocer la cantidad de 'Input Features' hago lo siguiente
len(X_train[0])

11

In [26]:
# Dense : define la sinapsis (cantidad de 'Input Features' que recibira la 'Hidden Layer'), y define la 'Hidden Layer' y sus 'Output Features'.
# Units : por recomendacion del profesor se escojen la cantidad de neuronas que corresponden a la media de 'Input Features'.
# Input_Dim : definimos la cantidad de 'Input Features' que recibira la 'Hidden Layer'.
# Kernel:Inicializer : definimos los valores de inicializacion de los parametros de la ANN.
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# 'Hidden Layer' 2
# 'Input_Dim' no es necesario especificarla (no especificar la cantidad de 'Input Features')
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# 'Output Layer'
# Modelo de Clasificacion (dos clases de salida).
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

## Compilar la ANN

In [27]:
# optimizar : Optimization Function como Stochastic Greadient Descent.
# loss : Error/Costo Function.
# metrics : metrica de para ir visualizando el rendimiento del entrenamiento del modelo.
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training del modelo de ANN

In [28]:
# batch_size : contenedor/porcion de datos del conjunto de datos de entrenamiento de 32 datos.
# --> ingesta de paquetes de 32 datos a la ANN para que se entrene.
# epochs : numero de ingesta completa del conjunto de datos de entrenamiento a la ANN.
classifier.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 4s 2ms/step - loss: 0.5787 - accuracy: 0.7950
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4371 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4319 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4300 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4281 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4261 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4241 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4220 - accuracy: 0.7994
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4199 - accuracy: 0.8192
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4182 - accura

## Prediccion y evaluacion de la ANN

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
# Trnasformar los datos de prediccion a booleanos.
# --> los verdaderos son clientes que se van del banco.
# --> los falsos son clientes que se quedan en el banco.
print(y_pred)
print(y_pred > 0.5)

[[0.24607418]
 [0.31993186]
 [0.12808429]
 ...
 [0.17841029]
 [0.13685305]
 [0.12348044]]
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

ValueError: ignored

## Probar la ANN con un dato nuevo

###Utiliza nuestro modelo de RNA para predecir si el cliente con la siguiente información abandonará el banco:

*   Geografia: Francia (dos columnas)
*   Puntaje de crédito: 600
*   Género masculino
*   Edad: 40 años de edad
*   Tenencia: 3 años.
*   Saldo: $ 60000

*   Número de productos: 2
*   ¿Este cliente tiene una tarjeta de crédito? Sí
*   ¿Es este cliente un miembro activo? Sí
*   Salario estimado: $ 50000

In [32]:
dataset.iloc[0, 3:13].values

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [33]:
X[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [34]:
# En el DataSet son 3 paises, por lo cual son dos columnas para especificar a cual corresponde (Variable Dummy)
# Escalar los datos de la nueva prediccion con : sc_X.transform()
# new_prediction = classifier.predict(sc_X.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = classifier.predict(sc_X.transform(np.array([[0,0,600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
print(new_prediction)
print(new_prediction > 0.5)

[[0.09336352]]
[[False]]


In [35]:
print((cm[0][0]+cm[1][1])/cm.sum())

NameError: ignored

# Parte 2 - Evaluar, Mejorar y ajustar la RNA

## Evaluar la RNA

In [36]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.layers import Dropout

### Crear el Modelo.
### Dropuot : es para evitar el Overfitting apagando un porcentje de neuronas en cada capa.

In [69]:
def build_classifier():

  # Inicializar la ANN
  classifier = Sequential()

  # Añadir capa de entrada y primera capa oculta
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

  # Capa Dropuot (apagar neuronas para evitar el Overfitting) a la primera 'Hidden Layer'
  # p = porcentaje de apagado de neuronas en la capa.
  classifier.add(Dropout(0.5))

  # Añadir segunda capa oculta
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

  # Capa Dropuot (apagar neuronas para evitar el Overfitting) a la segunda 'Hidden Layer'
  classifier.add(Dropout(0.5))

  # Añadir capa de salida
  classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

  # Compilar la ANN
  classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

  # Devolder el modelo de calsificacion
  return classifier

In [70]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 32, nb_epoch = 10)
# cv : cross validations --> de decimos de 32, lo que significa que tomara lotes de 32 datos y
# dividira entre entrenamiento y testing, variandolos en cada iteracion para que todos los datos
# se usen tanto en Training como en Testing (K-Fold Cross Validation)
# n_jobs : le decimos que use todos los recursos posibles que pueda tener del hardware (pc)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 32, verbose = 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


8/8 [==============================] - 0s 4ms/step - loss: 0.5233 - accuracy: 0.7840


[Parallel(n_jobs=1)]: Done  32 out of  32 | elapsed:   54.9s finished


In [71]:
accuracies

array([0.81599998, 0.76800001, 0.77999997, 0.77200001, 0.80400002,
       0.796     , 0.77200001, 0.80000001, 0.80000001, 0.81999999,
       0.78399998, 0.77200001, 0.77999997, 0.81599998, 0.83200002,
       0.80800003, 0.85600001, 0.81599998, 0.75199997, 0.81199998,
       0.77600002, 0.764     , 0.78799999, 0.792     , 0.80800003,
       0.80800003, 0.77600002, 0.81999999, 0.796     , 0.80800003,
       0.796     , 0.78399998])

In [72]:
mean = accuracies.mean()
variance = accuracies.std() # Una varianza sobre 0,1 es alta.
print(mean)
print(variance)

0.7960000019520521
0.021886070768843597


## Mejorar la ANN
### Dropout para evitar el Overfitting
#### Esto se hace arriba en la creacion del modelo.

In [ ]:
# from keras.layers import Dropout
# Añadir capa de entrada y primera capa oculta
# classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Capa Dropuot (apagar neuronas para evitar el Overfitting) a la primera 'Hidden Layer'
# p = porcentaje de apagado de neuronas en la capa.
# classifier.add(Dropout(p = 0.17))

# Ajustar la ANN

In [51]:
# Esta funcion prueba todas las combinaciones posibles que pueden tener los hiperparametros
# del modelo, lo hace para encontrar el mejor modelo posible.
from sklearn.model_selection import GridSearchCV

### Creacion del Modelo

In [52]:
def build_classifier(optimizer):

  # Inicializar la ANN
  classifier = Sequential()

  # Añadir capa de entrada y primera capa oculta
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

  # Capa Dropuot (apagar neuronas para evitar el Overfitting) a la primera 'Hidden Layer'
  # p = porcentaje de apagado de neuronas en la capa.
  # classifier.add(Dropout(p = 0.1))

  # Añadir segunda capa oculta
  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

  # Capa Dropuot (apagar neuronas para evitar el Overfitting) a la segunda 'Hidden Layer'
  # classifier.add(Dropout(p = 0.1))

  # Añadir capa de salida
  classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

  # Compilar la ANN
  classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])

  # Devolder el modelo de calsificacion
  return classifier

In [53]:
classifier = KerasClassifier(build_fn = build_classifier)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.


In [54]:
parameters = {
    'batch_size': [32, 64, 128],
    'nb_epoch': [50, 100, 200],
    'optimizer': ['adam', 'rmsprop']
}

In [55]:
# Este metodo de ajuste para encontrar el mejor modelo no permite el 'Dropout' no se por que.
grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv = 10, n_jobs = -1)

In [56]:
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:705: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


250/250 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7962


In [57]:
print(best_parameters)

{'batch_size': 32, 'nb_epoch': 50, 'optimizer': 'adam'}


In [58]:
print(best_accuracy)

0.796
